name: Test youtube catalog code
on:
  pull_request:

jobs:
  test-compiles:
    runs-on: ubuntu-latest

    steps:
      -
        name: checkout from github
        uses: actions/checkout@v6

      -
        name: Run tests
        shell: bash
        env:
          TZ: 'EST'
          LC_TIME: 'en_US.UTF-8'
        run: |
          #set -e
          #locale
          'tests/module-tests.sh'
