name: 'Download the youtube video channel inventory'
on:
  workflow_dispatch:

jobs:
  list-videos:
    runs-on: 'ubuntu-latest'

    steps:
      -
        name: 'Checkout from github'
        uses: 'actions/checkout@v4'
        with:
          token: '${{ secrets.PAT }}'

      -
        name: 'Install jq'
        shell: 'bash'
        run: |
          which jq || (
            sudo apt-get update
            sudo apt-get install jq
          )

      -
        name: 'Install node'
        shell: 'bash'
        run: |
          sudo apt-get update
          sudo apt-get install nodejs npm

      -
        name: 'Install pino-pretty'
        shell: 'bash'
        run: |
          sudo npm -g install pino-pretty

      -
        name: 'Get videos'
        shell: 'bash'
        env:
          YOUTUBE_ACCESS_TOKEN: '${{ secrets.YOUTUBE_ACCESS_TOKEN }}'
          VIDEO_DB: 'content/video-list.json'
        run: |
          jq . "${VIDEO_DB}" > /dev/null
          ( src/playground.sh > /tmp/video-list.json ) 2>&1 | pino-pretty -t
          mv /tmp/video-list.json "${VIDEO_DB}"
          jq . "${VIDEO_DB}" > /dev/null

      - name: 'Commit video listing'
        env:
          CI_COMMIT_MESSAGE: 'Automatic video retrieval'
          CI_COMMIT_AUTHOR: 'github-ci'
          CI_COMMIT_EMAIL: 'github-ci@users.noreply.github.com'
        run: |
          git config --global user.name "${CI_COMMIT_AUTHOR}"
          git config --global user.email "${CI_COMMIT_EMAIL}"
          git add content
          git commit -m "${CI_COMMIT_EMAIL}"
          git push
