name: 'Download the youtube video channel inventory'
on:
  workflow_dispatch:

jobs:
  list-videos:
    runs-on: 'ubuntu-latest'

    steps:
      -
        name: 'Checkout from github'
        uses: 'actions/checkout@v6'
        with:
          token: '${{ secrets.PAT }}'

      -
        name: 'Install pino-pretty'
        shell: 'bash'
        run: |
          sudo npm -g install pino-pretty

      -
        name: 'Get access token'
        id: 'access'
        shell: 'bash'
        env:
          YOUTUBE_REFRESH_TOKEN: '${{ secrets.YOUTUBE_REFRESH_TOKEN }}'
          YOUTUBE_CLIENT_ID: '${{ vars.YOUTUBE_CLIENT_ID }}'
          YOUTUBE_CLIENT_SECRET: '${{ secrets.YOUTUBE_CLIENT_SECRET }}'
        run: |
          exec {fdLog}>&1
          (
            source 'src/lib/bash-pino-trace.sh'
            source 'src/lib/call-rest.sh'

            method='POST'
            curlMethodArgs=(
              '--header' 'Accept: application/json'
            )

            curlMethod \
              --url 'https://www.googleapis.com/oauth2/v4/token' \
              --data-urlencode "client_id=${YOUTUBE_CLIENT_ID}" \
              --data-urlencode "client_secret=${YOUTUBE_CLIENT_SECRET}" \
              --data-urlencode "refresh_token=${YOUTUBE_REFRESH_TOKEN}" \
              --data-urlencode 'grant_type=refresh_token' >/tmp/out.json

            jq --raw-output '"::add-mask::\(.access_token)"' /tmp/out.json
            jq . /tmp/out.json
            jq --raw-output '"YOUTUBE_ACCESS_TOKEN=\(.access_token)"' /tmp/out.json | tee -a "${GITHUB_OUTPUT}"
          ) | pino-pretty -t

      -
        name: 'Get videos'
        shell: 'bash'
        env:
          YOUTUBE_ACCESS_TOKEN: '${{ steps.access.outputs.YOUTUBE_ACCESS_TOKEN }}'
          VIDEO_DB:    'content/video-list.json'
        run: |
          ( src/youtube-videos.sh > "${VIDEO_DB}" ) 2>&1 | pino-pretty -t

      -
        name: 'Get playlists'
        shell: 'bash'
        env:
          YOUTUBE_ACCESS_TOKEN: '${{ steps.access.outputs.YOUTUBE_ACCESS_TOKEN }}'
          PLAYLIST_DB: 'content/play-list.json'
        run: |
          ( src/youtube-playlists.sh > "${PLAYLIST_DB}" ) 2>&1 | pino-pretty -t

      - name: 'Commit video listing'
        env:
          CI_COMMIT_MESSAGE: 'Automatic video retrieval'
          CI_COMMIT_AUTHOR: 'github-ci'
          CI_COMMIT_EMAIL: 'github-ci@users.noreply.github.com'
        run: |
          git config --global user.name "${CI_COMMIT_AUTHOR}"
          git config --global user.email "${CI_COMMIT_EMAIL}"
          git add content
          git commit -m "${CI_COMMIT_EMAIL}"
          git push
